Update xgl from commit: fc379ee * Enable VK_EXT_scalar_block_layout extension * Enable VK_KHR_swapchain_mutable_format extension * Enable on-chip GSVS ring on GFX9, seeing up to 10% performance gain * Update base address offset calculation to be per device * Use SW compositor path for MGPU in windowed modes * Add missing files to CMakelist to fix undefined reference to vk::OverrideDispatchTable_ND(vk::DispatchTable*) * Fix errors with multiple monitors and direct display * Add dccBitsPerPixelThreshold setting * Fix the issue that Pipeline keeps a reference to layout after it is created * Fix dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail test failure * Fix a crash issue on Raven caused by the implementation of VK_AMD_memory_overallocation_behavior extension * Fix calculation of the pRegions offset in CmdBuffer::PalCmdResolveImage()